apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-userlist-secret
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    helm.sh/chart: {{ template "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  userlist.txt: {{ include "pgbouncer.secret.userlist" . | trim | b64enc }}
